name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Или 'master', если это ваша основная ветка

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Укажите вашу версию Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Add .nojekyll file   # Этот шаг добавит файл .nojekyll в папку build
        run: touch build/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build